### ISSUE TITLE
Avoid dragons to spawn near bases

### ISSUE THREAD

**Issue by Artwind2** [AlexModGuy/Ice-and-Fire-Suggestions#175]
It could be great to have the possibilty to avoid the spawning of the dragons in some places.
I've got a very bad luck when coming back to my base after several in game days exloring and found it half devastated by a dragon.
Incorporate a new block and say that no dragon can spawn in his field of action could be a solution ?

Thanks

**Comment by RealisticMC73309** [comment]
Dragons don't spawn like other mobs. They only spawn at a dragon nest or cave. They only solution to stop them from destroying your base is too not make it near a dragon nest. Since they wander try to kill or hide all passive mobs in the area of your base to prevent them from wandering into your base.
