### ISSUE TITLE
[Suggestion] Kraken! Aka: Giant squid/octopus

### ISSUE THREAD

**Issue by TonyBouru** [AlexModGuy/Ice-and-Fire-Suggestions#188]
I was thinking, it would be cool to see a water boss in this mod, like a Kraken! It would be big, but not too big and it can be found in a specific biome/island area of the ocean. I can see you guys are doing a mythology theme in the mod so why not a Kraken?

**Comment by Theamericanpilot** [comment]
the kraken... there are many ways a kraken has been precieved but the just a giant squid that swallows ship is quite inaccurate the norse kraken was a giant beast with many tenticles the large enough to have a village on its back since its back is very island like and then for some lore: ''Tales of unnknowing people setteling on this beast then getting dragged down to the abyss''

**Comment by PCAwesomeness** [comment]
@Theamericanpilot 

Fire-breathing dragons are also "inaccurate" to the original myths, yet we have them. It just depends on what's actually unique and what's just flat-out bad.

Also, we have a lot of fish-like creatures in the mod, while there are no cephalopod monsters.
