### ISSUE TITLE
Silver update ?

### ISSUE THREAD

**Issue by TheSaltyFox** [AlexModGuy/Ice-and-Fire-Suggestions#343]
Hi,

To be quick and make it understadable, Silver isn't so usefull, but still cool !... But not usefull...
I noticed that when I was crafting a new dragon bone flute in a brand new game, and I was surprised by the fact that it doesn't need silver to craft it... Then, I looked to the utility, I learn that there is a very few items need silver to be crafted, and they're not so usefull.
I suggest adding new items or change some craft to fit with silver that will make it finaly almost essential in the mod. For example, using the silver to make armor that have unique habilities with silver only (using fire dragon's blood in a silver armor weared by a ice dragon to increase his resistance agains't fire), add some silver ingot or kind of "smelted silver" in food to make dragon growning up twice or four times quicker, crafting silver to create a "Silver incubator" using dragons' blood to make it working, combine silver to dragons' bone and blood to craft ice/fire sword, combine silver armor with dragon's blood to give resistance against them, etc etc...

Silver has a huge potential, but you didn't seem to work on it anymore :/

Anyway, the mod still awesome, you're doing a damn great work, I can't play minecraft without this mod anymore.

Thx for all of you <3

**Comment by TheOneTraveler** [comment]
no. that's not it chief.

**Comment by TheSaltyFox** [comment]
What do you mean by that ?

**Comment by TheOneTraveler** [comment]
silver is a holy metal that is damaging to cursed, or undead mobs, that is it's purpose. im sure it will be very useful once the wendigo, ghosts, and vampires are added, even more so once the werewolves are added because they'll do all that extra damage to werewolves. all these other things you mentioned in this suggestion dont work with the original concept and dont make much sense logically. they're also poorly thought out mechanics, if im being blunt about it.

**Comment by zucaluca** [comment]
I like the last idea about adding silver and dragons blood to the flamed/iced bone sword making process. Would make it more of a challenge to make.
